### PR TITLE
Fix null pointer in delegator when address is not resolvable

### LINKED ISSUE #1387: NullpointerException on non-resolvable DNS + stall DNS
This issue is with the following topology:
Linkerd -> namerd -> consul

Consul stores the service info and address  is an elb DNS [ x ]

Here is the observation:
if x doesn’t exist -> linkerd reports nullpointexception for the specific dst
And by adding x into R53, still nullpointerexception (yes: **ttl** is set : networkaddress.cache.ttl=30 )
Restart Linkerd solved the problem

Repro on 1.1.0 linkerd / namerd 
```
un 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]: E 0613 23:50:37.457 UTC THREAD29 TraceId:1dfda261a57b95cd: addr on /#/io.l5d.consul/us-east-1/integration/clicktocall
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]: org.apache.thrift.TApplicationException: Internal error processing addr: 'java.lang.NullPointerException'
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.decodeResponse(Namer$FinagleClient.scala:65)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.$anonfun$addr$1(Namer$FinagleClient.scala:170)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.thrift.DeserializeCtx.deserialize(DeserializeCtx.scala:38)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.$anonfun$addr$3(Namer$FinagleClient.scala:194)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1089)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.runq(Promise.scala:406)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.update(Promise.scala:775)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.setValue(Promise.scala:751)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:181)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.codec.BufCodec$.channelRead(BufCodec.scala:59)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.channel.AnyToHeapInboundHandler$.channelRead(AnyToHeapInboundHandler.scala:36)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelRead(ChannelRequestStatsHandler.scala:42)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelRead(ChannelStatsHandler.scala:92)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by adleong**
Fixes #1387 (probably)

If the delegator gets an unresolvable address, it throws a
NullPointerException.

Check that the address is not null before using it in a delegation.

I wasn't able to reproduce this issue because unresolable addresses appear as
Negs for me.  It's unclear to me how to get an Addr.Bound with an unresolvable
address in it.  However, based on the stack trace in the bug report, this
should fix the problem.

### CODE REVIEW

File: admin/src/main/scala/io/buoyant/admin/names/DelegateApiHandler.scala [hunk 1]
```diff
@@ -30,8 +30,10 @@ object DelegateApiHandler {
   case class Address(ip: String, port: Int, meta: Map[String, Any])
   object Address {
     def mk(addr: FAddress): Option[Address] = addr match {
-      case FAddress.Inet(isa, meta) => Some(Address(isa.getAddress.getHostAddress, isa.getPort, meta))
-      case _ => None
+      case FAddress.Inet(isa, meta) if isa.getAddress != null =>
+        Some(Address(isa.getAddress.getHostAddress, isa.getPort, meta))
```
Comment (olix0r) [inline admin/src/main/scala/io/buoyant/admin/names/DelegateApiHandler.scala]: could avoid doing getAddress twice with:

```scala
case FAddress.Inet(isa, meta) =>
  Option(isa.getAddress).map { a => Address(a.getHostAddress, isa.getPort, meta) }
```
