### PR TITLE
Try to reconnect to consul after ConnectionFailedException

### LINKED ISSUE #1230: Consul namer does not pick up on changes in consul anymore after consul was not reachable
We are using linkerd with a consul namer. If there was a short connection error to consul for whatever reasons, linkerd seems to fail to re-connect to consul and will not receive any updates on where a service is available from consul anymore.

How to reproduce:

Tested with linkerd 0.9.0 and consul 0.8.1

Start a random web-service, in this case running on port 9012

Consul Config:

```
{
    "service": {
        "name": "my-service", 
        "port": 9012
    }, 
    "checks": [
        {
            "name": "my-service-health",
            "http": "http://localhost:9012/health",
            "service_id": "my-service",
            "interval": "5s"
        }
    ]
}
```

Start consul

```
consul agent -dev -advertise 127.0.0.1 -config-dir=/path/to/config
```

Linkerd config:

```
admin:
  port: 9991

namers:
- kind: io.l5d.consul
  host: localhost
  port: 8500
  useHealthCheck: true

routers:
- protocol: http
  dtab: |
    /svc  => /#/io.l5d.consul/dc1;
  label: consul
  servers:
  - port: 4140
    ip: 0.0.0.0

```

Start linkerd

```
linkerd ./linkerd.yaml
```

Do a request to my-service via linkerd

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
HTTP/1.1 200 OK
...
```

Now kill my-service. and do another request for this service to linkerd

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
```

The request returns a 502.

In the linkerd log you see the expected
```
0420 15:30:51.422 UTC THREAD19 TraceId:1f9aa75f534a156b: #/io.l5d.consul/dc1/my-service: name resolution is negative (local dtab: Dtab())
E 0420 15:30:52.245 UTC THREAD22 TraceId:c0f9420907d4ff25: service failure
com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/my-service, Dtab.base=[/svc=>/#/io.l5d.consul/dc1], Dtab.local=[]. Remote Info: Not Available
```

Start my-service again.

Subsequent requests to my-service via linkerd will of course work again

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
HTTP/1.1 200 OK
...
```

Now stop consul and start it again

The linkerd log shows:

```
Failure(java.net.ConnectException: Connection refused: localhost/127.0.0.1:8500. Remote Info: Upstream Address: /127.0.0.1:51163, Upstream Client Id: Not Available, Downstream Address: localhost/127.0.0.1:8500, Downstream Client Id: #/io.l5d.consul, Trace Id: 73204f8c5072fd90.73204f8c5072fd90<:73204f8c5072fd90, flags=0x10) with NoSources
Caused by: com.twitter.finagle.ChannelWriteException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:8500. Remote Info: Upstream Address: /127.0.0.1:51163, Upstream Client Id: Not Available, Downstream Address: localhost/127.0.0.1:8500, Downstream Client Id: #/io.l5d.consul, Trace Id: 73204f8c5072fd90.73204f8c5072fd90<:73204f8c5072fd90
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:8500
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
    at java.lang.Thread.run(Thread.java:745)
```

Now kill my-service. and do another request for this service to linkerd

```
$ curl http://localhost:4140/ -H 'Host: my-service' -I
```

The request returns a 502 but linkerd still tries to connecto to port 9012 even though this is down in consul.

From the linkerd log

```
E 0420 15:11:47.832 UTC THREAD28 TraceId:0a943f473a987f04: service failure
com.twitter.finagle.ChannelWriteException: java.net.ConnectException: Connection refused: /127.0.0.1:9012. Remote Info: Upstream Address: /127.0.0.1:51799, Upstream Client Id: Not Available, Downstream Address: /127.0.0.1:9012, Downstream Client Id: #/io.l5d.consul/dc1/my-service, Trace Id: 0a943f473a987f04.0a943f473a987f04<:0a943f473a987f04
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:9012
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.twitter.finagle.util.ProxyThreadFactory$$anonfun$newProxiedRunnable$1$$anon$1.run(ProxyThreadFactory.scala:19)
    at java.lang.Thread.run(Thread.java:745)
```

If I query consul for running nodes it returns nothing:

```
curl http://localhost:8500/v1/health/service/my-service\?passing\=true
[]
```

So after the short consul restart linkerd apparently did not connect back to consul and did not pick up of the change that there is no host available anymore for the requested service, but still tries to connecto to some (probably) cached information.
We observerd the same behavior if we add/remove hosts to consul.

### PR DESCRIPTION
**Pull request by esbie**
Problem:
Sometimes on consul restart linkerd stops talking to consul, causing a stale lookup cache.
As consul is starting up, linkerd tries to connect and fails. Then never tries again.

Solution:
Remove the RequeueFilter from the client stack so that connection failures are no longer flagged as NonRetryable. Fixes #1230

### CODE REVIEW

File: namer/consul/src/main/scala/io/buoyant/namer/consul/DcServices.scala [hunk 1]
```diff
@@ -62,7 +62,14 @@ private[consul] object DcServices {
             // may consider retrying certain failures (with backoff).
             state() = Activity.Failed(e)
             stats.errors.incr()
-            Future.exception(e)
+            log.debug("consul connection failed: %s", name)
+
+            e match {
```
Comment (adleong) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/DcServices.scala]: Instead of adding an extra layer of retrying here, would it be possible to add ConnectionFailedException to the RetryPolicy in BaseApi.infiniteRetryFilter so that it will retry on ConnectionFailedExceptions instead of giving up?

Comment (esbie) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/DcServices.scala]: good point, let me test it out

Comment (esbie) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/DcServices.scala]: I'm not 100% sure what's going on here, but when `ConnectionFailedException` happens (or connection refused or connection time out), `BaseApi` doesn't seem to call the backoff retry policy at all. I am sort of assuming the exception is happening in `client` and then the retry filter and api filter are skipped.

So this is a long way of saying I couldn't get it to work by adding something like
```
case (req, Throw(Failure(Some(err: ConnectionFailedException)))) => true
```
but I'm open to suggestions. I guess I could dig around in finagle to better understand how `Http.client` works...

Comment (adleong) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/DcServices.scala]: hmmmm... strange.  The only thing I can think of is that RetryFilter will skip any Failures that are flagged `f.isFlagged(FailureFlags.NonRetryable)` without consulting the retry policy.  Maybe the connection failed exceptions are flagged this way?  Not sure why they would be though....

Comment (esbie) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/DcServices.scala]: yeah you called it, the failures are flagged as both rejected and nonretryable. Looking around some in finagle I don't see where those are set or how to configure them. RetryFilter/RequeueFilter seem to be the primary users of the nonretryable flag

File: namer/consul/src/main/scala/io/buoyant/namer/consul/ConsulInitializer.scala [hunk 2]
```diff
@@ -60,6 +61,7 @@ case class ConsulConfig(
   @JsonIgnore
   def newNamer(params: Stack.Params): Namer = {
     val service = Http.client
+      .withStack(Http.client.stack.remove(Retries.Role))
```
Comment (olix0r) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/ConsulInitializer.scala]: Oh wait. Should this be requeues?  Do we depend on the retry behavior?

Comment (adleong) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/ConsulInitializer.scala]: This is `Retries.moduleRequeueable` which is the requeues module, included by the stack client by default.

Comment (olix0r) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/ConsulInitializer.scala]: perhaps a comment that this removes Requeues and that the retries filter still applies? (It does, right?)

**Comment by esbie** [comment]
We don't have a consul e2e test that I know of. I've been manually testing using the steps laid out here: https://github.com/linkerd/linkerd/issues/1230#issuecomment-297831954.

File: namer/consul/src/main/scala/io/buoyant/namer/consul/ConsulInitializer.scala (hunk 2 above)
Comment (esbie) [inline namer/consul/src/main/scala/io/buoyant/namer/consul/ConsulInitializer.scala]: Sure I can add a comment, I find this role pretty confusing too. `infiniteRetryFilter` defined in `BaseApi` still applies.

**Comment by Ashald** [comment]
Hm, there is no entry in `CHANGES.md` for this - is it intentionally or you just forgot to add it? :)

**Comment by esbie** [comment]
forgot to add, thanks :)

**Comment by Ashald** [comment]
Thanks for fixing it! :)
