### PR TITLE
Always clear the x-forwarded-client-cert header

### LINKED ISSUE #2068: x-forwarded-client-cert in external request isn't (always) filtered out
- [x] Bug report

**What happened**:

linkerd doesn't remove the `x-forwarded-client-cert` header field from inbound requests.

**What you expected to happen**:

When linkerd receives a `x-forwarded-client-cert` header field in a request, it must remove it or it must reject the request. It must never forward the `x-forwarded-client-cert` header field because that would allow any client to forge the identity of other clients if the inner application is relying on the `x-forwarded-client-cert` header field. (Also some applications may look at the `x-forwarded-client-cert` to determine if the request was sent over HTTPS or HTTP.)

**Anything else we need to know?**:

This could be a security-sensitive issue for any application relying on the `x-forwarded-client-cert` being accurate.

This filtering probably must happen regardless of the setting that enables linkerd's injection of the header field.

There may be other header fields that need to be always replaced/filtered in a similar way.

### PR DESCRIPTION
**Pull request by adleong**
When Linkerd receives a x-forwarded-client-cert header field in a request, it must remove it or it must reject the request. It must never forward the x-forwarded-client-cert header field because that would allow any client to forge the identity of other clients if the inner application is relying on the x-forwarded-client-cert header field. (Also some applications may look at the x-forwarded-client-cert to determine if the request was sent over HTTPS or HTTP.)

Always clear any incoming x-forwarded-client-cert header.

Fixes #2068 

Signed-off-by: Alex Leong <alex@buoyant.io>

### CODE REVIEW

File: linkerd/protocol/http/src/integration/scala/io/buoyant/linkerd/protocol/ForwardClientCertTest.scala [hunk 1]
```diff
@@ -69,4 +70,49 @@ class ForwardClientCertTest extends FunSuite {
...
+    val router = linker.routers.head.initialize()
+    val server = router.servers.head.serve()
+
+    val client = Upstream.mk(server)
+
+    try {
+      val rsp = {
+        val req = Request()
+        req.host = "clifford"
+        req.headerMap(ForwardClientCertFilter.Header) = "totally_bogus"
```
Comment (briansmith) [inline linkerd/protocol/http/src/integration/scala/io/buoyant/linkerd/protocol/ForwardClientCertTest.scala]: It would be good to have a test where the value is syntactically valid to ensure that it is removed even when it looks good, and not only when it is "totally bugus."

Comment (briansmith) [reply linkerd/protocol/http/src/integration/scala/io/buoyant/linkerd/protocol/ForwardClientCertTest.scala]: It would also be good to have a test that shows that if there are multiple instances of the header field that all of them are removed.
