### PR TITLE
Fix handling of unspecified TLS configs (#1436)

### LINKED ISSUE #1436: "File does not contain valid certificates" when trustCerts not specified in TLS client (v1.1.0 only)
When a basic config is provided to use a tls client where trustCerts is _not_ specified, linkerd **v1.1.0** responds with `HTTP/1.1 502 Bad Gateway` when issued the following curl statement: `curl -x localhost:4140 -X GET http://www.google.com:443 -sI | head -n 1`. 

The error log reports `File does not contain valid certificates: /tmp/certCollection1848457118942697108.tmp`. 

When linkerd **v1.0.2** is used with the exact same config and curl command, it responds with `HTTP/1.1 200 OK`.

For reference, here's the TLS client config:
```
    kind: io.l5d.static
    configs:
    - prefix: "/$/io.buoyant.rinet/443/{service}"
      tls:
        commonName: "{service}"
```
Here's the error log:
```
E 0621 20:04:51.016 UTC THREAD21 TraceId:d186a04959f5bc12: service failure
java.lang.IllegalArgumentException: File does not contain valid certificates: /tmp/certCollection1848457118942697108.tmp
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:164)
	at com.twitter.finagle.netty4.ssl.Netty4SslConfigurations$.configureTrust(Netty4SslConfigurations.scala:40)
	at com.twitter.finagle.netty4.ssl.client.Netty4ClientEngineFactory.apply(Netty4ClientEngineFactory.scala:63)
	at com.twitter.finagle.netty3.Netty3Transporter.$anonfun$addFirstTlsHandlers$1(Netty3Transporter.scala:307)
	at com.twitter.finagle.netty3.Netty3Transporter.$anonfun$addFirstTlsHandlers$1$adapted(Netty3Transporter.scala:306)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.finagle.netty3.Netty3Transporter.addFirstTlsHandlers(Netty3Transporter.scala:306)
	at com.twitter.finagle.netty3.Netty3Transporter.newPipeline(Netty3Transporter.scala:382)
	at com.twitter.finagle.netty3.Netty3Transporter.newConfiguredChannel(Netty3Transporter.scala:391)
	at com.twitter.finagle.netty3.Netty3Transporter.$anonfun$apply$2(Netty3Transporter.scala:398)
	at com.twitter.finagle.netty3.ChannelConnector.apply(Netty3Transporter.scala:48)
	at com.twitter.finagle.netty3.Netty3Transporter.apply(Netty3Transporter.scala:400)
	at com.twitter.finagle.netty3.Netty3Transporter$$anon$3.apply(Netty3Transporter.scala:149)
	at com.twitter.finagle.Http$Client$$anon$2.$anonfun$apply$1(Http.scala:209)
	at com.twitter.util.Local.letClear(Local.scala:151)
	at com.twitter.finagle.context.MarshalledContext.letClearAll(MarshalledContext.scala:112)
	at com.twitter.finagle.context.Contexts$.$anonfun$letClearAll$1(Contexts.scala:38)
	at com.twitter.util.Local.letClear(Local.scala:151)
	at com.twitter.finagle.context.LocalContext.letClearAll(LocalContext.scala:43)
	at com.twitter.finagle.context.Contexts$.letClearAll(Contexts.scala:37)
	at com.twitter.finagle.Http$Client$$anon$2.apply(Http.scala:209)
	at com.twitter.finagle.Filter$AndThen$$anon$3.apply(Filter.scala:149)
	at com.twitter.finagle.pool.CachingPool.apply(CachingPool.scala:58)
	at com.twitter.finagle.pool.WatermarkPool.apply(WatermarkPool.scala:144)
	at com.twitter.finagle.liveness.FailureAccrualFactory.apply(FailureAccrualFactory.scala:370)
	at com.twitter.finagle.service.ExceptionRemoteInfoFactory.apply(ExceptionRemoteInfoFactory.scala:71)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.loadbalancer.LoadBalancerFactory$StackModule$$anon$2.apply(LoadBalancerFactory.scala:208)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.loadbalancer.LeastLoaded$Node.apply(LeastLoaded.scala:30)
	at com.twitter.finagle.loadbalancer.Balancer.apply(Balancer.scala:250)
	at com.twitter.finagle.loadbalancer.Balancer.apply$(Balancer.scala:240)
	at com.twitter.finagle.loadbalancer.p2c.P2CLeastLoaded.apply(P2CLeastLoaded.scala:29)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.factory.TrafficDistributor$Distributor.apply(TrafficDistributor.scala:99)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.factory.TrafficDistributor.apply(TrafficDistributor.scala:303)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.factory.StatsFactoryWrapper.apply(StatsFactoryWrapper.scala:44)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.factory.RefcountedFactory.apply(RefcountedFactory.scala:24)
	at com.twitter.finagle.ServiceFactoryProxy.apply(Service.scala:227)
	at com.twitter.finagle.factory.TimeoutFactory.apply(TimeoutFactory.scala:61)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.service.Retries$$anon$1.applySelf(Retries.scala:225)
	at com.twitter.finagle.service.Retries$$anon$1.apply(Retries.scala:262)
	at com.twitter.finagle.Filter$$anon$2.apply(Filter.scala:99)
	at com.twitter.finagle.service.DelayedFactory.$anonfun$apply$1(DelayedFactory.scala:46)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1089)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
	at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
	at com.twitter.util.Promise.runq(Promise.scala:406)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
	at com.twitter.util.ExecutorServiceFuturePool$$anon$4.run(FuturePool.scala:141)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.cert.CertificateException: found no certificates in input stream
	at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:98)
	at io.netty.handler.ssl.PemReader.readCertificates(PemReader.java:64)
	at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:1026)
	at io.netty.handler.ssl.SslContextBuilder.trustManager(SslContextBuilder.java:162)
	... 72 more
```

### PR DESCRIPTION
**Pull request by hawkw**
Problem
--------

Somewhere between v1.0.2 and v1.10, a regression was introduced that caused configurations using a TLS client without specifying a list of certs to trust. I traced this issue to code which was handling TLS client configs with no trusted certs by transforming `None` into an empty list of certs, rather than handling that case separately with `TrustCredentials.Unspecified`.

Solution
--------

I rewrote the code in question to handle this case by using `TrustCredentials.Unspecified`, rather than attempting to use an empty temp file as a cert collection.

Validation
---------

Reproduced the problem exactly as described in issue #1436. The configuration in question is present in `examples/proxy.yml`, and can be tested with the `curl` command `curl -x localhost:4140 -X GET http://www.google.com:443 -sI | head -n 1`, as described in the issue. `linkerd` returns a HTTP 502 error on `master`, and HTTP 200 Ok on my branch (and on v1.0.2).

I also attempted to write an end to end test for this issue, but couldn't get  `TrustCredentials.Unspecified` them to work inside of the test environment – it appears that the client can't connect to a well-known certificate authority from within a test runner. Maybe ScalaTest isn't allowing connections to the outside network? I've pushed up the commented-out e2e tests regardless;  I'd like to get them working eventually.

Fixes #1436

### CODE REVIEW

File: finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala [hunk 1]
```diff
@@ -6,7 +6,8 @@ import com.twitter.finagle.ssl.{KeyCredentials, TrustCredentials}
 import com.twitter.finagle.ssl.client.{SslClientConfiguration, SslClientEngineFactory}
 import com.twitter.finagle.transport.Transport
 import com.twitter.io.StreamIO
-import java.io.{File, FileInputStream, FileOutputStream}
+import java.io._
+
```
Comment (adleong) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: rm empty line please

File: finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala [hunk 2]
```diff
@@ -25,17 +26,34 @@ case class TlsClientConfig(
...
-      val f = new FileOutputStream(certCollection)
-      for (cert <- trustStreams) StreamIO.copy(cert, f)
-      f.flush()
-      f.close()
-      certCollection.deleteOnExit()
+      // map over the optional certs parameter - we want to pass
+      // `TrustCredentials.CertCollection` if we were given a list of certs,
+      // but `TrustCredentials.Unspecified` (rather than an empty cert
+      // collection file) if we were not.
+      val credentials = certs map { certs: Seq[String] =>
```
Comment (adleong) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: `certs.map { ` please

Comment (adleong) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: we should be able to omit the explicit type annotation on the inner `certs`

File: finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala [hunk 3]
```diff
@@ -25,17 +26,34 @@ case class TlsClientConfig(
...
+        // a temporary file to hold the collection of certificates
+        val certCollection = File.createTempFile("certCollection", null)
+        // open the cert paths as Streams...
+        val f = certs.map { new FileInputStream(_) }
+          .foldLeft(new FileOutputStream(certCollection)) {
```
Comment (adleong) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: fold makes sense conceptually here but the fact that `StreamIO.copy` is side-effecting rather than pure means that this ends up being a bit more awkward than simply iterating over the trustStreams.

File: linkerd/protocol/http/src/e2e/scala/io/buoyant/linkerd/protocol/HttpTlsEndToEndTest.scala [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+    }
+
+    val req = Request(Method.Get, "/a/parf")
+    val rsp =
+      try await(client(req))
+      finally await(client.close().before(srv.close()))
+
+    assert(rsp.status == Status.Ok)
+  }
+//
```
Comment (adleong) [inline linkerd/protocol/http/src/e2e/scala/io/buoyant/linkerd/protocol/HttpTlsEndToEndTest.scala]: Add a brief comment explaining why this test is commented out.

File: finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala (hunk 1 above)
Comment (hawkw) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: I think IDEA adds those automatically - I'll have to find the config to make it not do that.

File: finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala (hunk 2 above)
Comment (hawkw) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: If I recall correctly, it wouldn't compile without that annotation? I'll double-check though.

Comment (hawkw) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: @adleong re `certs.map {`, I wasn't sure about that one – I know we avoid using infix notation, but I thought it was generally preferred for combinators like `map`, `flatMap`, etc, so I wasn't sure. Thanks for clearing that up.
