### PR TITLE
Fix ZooKeeper session management

### LINKED ISSUE #1829: namerd ZooKeeper session expired issue
Hi,

We are running namerd with linkerd (both 1.3.5) on DC/OS (1.10.4), namerd is using ZK as backend.
From time to time namerd ZK session is expiring, We can see in logs that it has established new session, but it doesn't work anymore. When this happens linkerd stops working also, until we restart namerd.

**namerd config:**
```
admin:
  port: 9001
  ip:   0.0.0.0
storage:
  kind: io.l5d.zk
  experimental: true
  zkAddrs:
  - host: master.mesos
    port: 2181
  pathPrefix: /dtabs
  sessionTimeoutMs: 10000
namers:
- kind:         io.l5d.marathon
  experimental: true
  prefix:       /io.l5d.marathon
  host:         marathon.mesos
  port:         8080
interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip:   0.0.0.0
  port: 4100
- kind: io.l5d.httpController
  ip:   0.0.0.0
  port: 4180
```

**linkerd config:**
```
admin:
  port: 9990
  ip:   0.0.0.0
telemetry:
- kind: io.l5d.prometheus

routers:
- protocol: http
  servers:
  - port: 4140
    ip: 0.0.0.0
  label: outgoing
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.marathon.mesos/4100
    transformers:
    # tranform all outgoing requests to deliver to incoming linkerd port 4141
    - kind: io.l5d.port
      port: 4141
  client:
    tls:
      commonName: linkerd
      trustCerts:
      - /ssl/root.pem
- protocol: http
  servers:
  - port: 4141
    ip: 0.0.0.0
    tls:
      certPath: /ssl/cert.pem
      keyPath: /ssl/key.pem
  label: incoming
  dtab: | # <-- this dtab strips off the transformer prefix
    /svc/%/io.l5d.port/4141 => /;
  identifier:
    kind: io.l5d.header
    header: l5d-dst-client # <-- use the client name picked by the outgoing router
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.marathon.mesos/4100
    transformers:
    - kind: io.l5d.localhost
```

**dtab:**
```
/marathonId  => /#/io.l5d.marathon ;
/srv         => /$/io.buoyant.http.domainToPathPfx/marathonId ;
/svc         => /srv ;
```
**Namerd log sample:**

```
W 0223 14:38:31.899 UTC THREAD18: Intermediate Failure session state: com.twitter.finagle.serverset2.client.SessionState$Disconnected$@1d72a477. Session: 2616af5330a03c7. Data is now unavailable.
W 0223 14:38:31.899 UTC THREAD18: Intermediate Failure session state: com.twitter.finagle.serverset2.client.SessionState$Disconnected$@1d72a477. Session: 2616af5330a03c7. Data is now unavailable.
W 0223 14:38:31.899 UTC THREAD18: Intermediate Failure session state: com.twitter.finagle.serverset2.client.SessionState$Disconnected$@1d72a477. Session: 2616af5330a03c7. Data is now unavailable.
W 0223 14:38:31.899 UTC THREAD18: Intermediate Failure session state: com.twitter.finagle.serverset2.client.SessionState$Disconnected$@1d72a477. Session: 2616af5330a03c7. Data is now unavailable.
W 0223 14:38:31.899 UTC THREAD18: Intermediate Failure session state: com.twitter.finagle.serverset2.client.SessionState$Disconnected$@1d72a477. Session: 2616af5330a03c7. Data is now unavailable.
E 0223 14:38:32.105 UTC THREAD18: Zookeeper session 2616af5330a03c7 has expired. Reconnecting in 10.milliseconds
I 0223 14:38:32.193 UTC THREAD10: Closing zk session 2616af5330a03c7
I 0223 14:38:32.216 UTC THREAD10: Starting new zk session 0
I 0223 14:38:32.317 UTC THREAD18: New ZKSession is connected. Session ID: 3616ac3a1170437
E 0223 14:40:07.901 UTC THREAD34 TraceId:5c46f17f6d53083a: binding name /svc/bpvoa.prd.crow
java.lang.Exception: session expired
	at com.twitter.finagle.serverset2.buoyant.ZkSession.$anonfun$watchedOperation$5(ZkSession.scala:162)
	at com.twitter.finagle.serverset2.buoyant.ZkSession.$anonfun$watchedOperation$5$adapted(ZkSession.scala:142)
	at com.twitter.util.Witness$$anon$17.notify(Event.scala:454)
	at com.twitter.util.Var$$anon$3.$anonfun$register$1(Var.scala:102)
	at com.twitter.util.Var$$anon$3.$anonfun$register$1$adapted(Var.scala:101)
	at com.twitter.util.Var$Observer.publish(Var.scala:156)
	at com.twitter.util.UpdatableVar.$anonfun$update$3(Var.scala:475)
	at com.twitter.util.UpdatableVar.$anonfun$update$3$adapted(Var.scala:470)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:153)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.twitter.util.UpdatableVar.update(Var.scala:470)
	at com.twitter.finagle.serverset2.client.EventDeliveryThread$.run(EventDeliveryThread.scala:18)

E 0223 14:40:08.053 UTC THREAD38 TraceId:f5717c33d711686d: binding name /svc/jobexecution.prd.crow
java.lang.Exception: session expired
	at com.twitter.finagle.serverset2.buoyant.ZkSession.$anonfun$watchedOperation$5(ZkSession.scala:162)
	at com.twitter.finagle.serverset2.buoyant.ZkSession.$anonfun$watchedOperation$5$adapted(ZkSession.scala:142)
	at com.twitter.util.Witness$$anon$17.notify(Event.scala:454)
	at com.twitter.util.Var$$anon$3.$anonfun$register$1(Var.scala:102)
	at com.twitter.util.Var$$anon$3.$anonfun$register$1$adapted(Var.scala:101)
	at com.twitter.util.Var$Observer.publish(Var.scala:156)
	at com.twitter.util.UpdatableVar.$anonfun$update$3(Var.scala:475)
	at com.twitter.util.UpdatableVar.$anonfun$update$3$adapted(Var.scala:470)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.RedBlackTree$._foreachKey(RedBlackTree.scala:109)
	at scala.collection.immutable.RedBlackTree$.foreachKey(RedBlackTree.scala:105)
	at scala.collection.immutable.TreeSet.foreach(TreeSet.scala:153)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at com.twitter.util.UpdatableVar.update(Var.scala:470)
	at com.twitter.finagle.serverset2.client.EventDeliveryThread$.run(EventDeliveryThread.scala:18)
```

**linkerd log sample :**
```
 0223 15:41:03.950 UTC THREAD10: Reaping /svc/bpavscan.prd.crow
E 0223 15:41:06.120 UTC THREAD10 TraceId:830a04e92c3b0996: addr on /#/io.l5d.marathon/crow/prd/bpavscan
Failure(Released, flags=0x02) with RemoteInfo -> Upstream Address: /43.194.55.109:37550, Upstream id: Not Available, Downstream Address: namerd.marathon.mesos/43.194.55.108:4100, Downstream label: interpreter/io.buoyant.namerd.iface.NamerdInterpreterConfig, Trace Id: 882938de6c3878ab.882938de6c3878ab<:882938de6c3878ab with Service -> interpreter/io.buoyant.namerd.iface.NamerdInterpreterConfig
```

**ZK log sample:**
```
Feb 23 14:38:30 euegisdcosprdm01v java[12429]: [myid:1] INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /43.194.55.105:54576 which had sessionid 0x2616af5330a03c7
host =	euegisdcosprdm01v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:30 euegisdcosprdm01v java[12429]: [myid:1] INFO  [QuorumPeer[myid=1]/0.0.0.0:2181:ZooKeeperServer@680] - Invalid session 0x2616af5330a03c7 for client /43.194.55.105:54576, probably expired
host =	euegisdcosprdm01v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:30 euegisdcosprdm01v java[12429]: [myid:1] INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:Learner@108] - Revalidating client: 0x2616af5330a03c7
host =	euegisdcosprdm01v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:30 euegisdcosprdm01v java[12429]: [myid:1] INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@935] - Client attempting to renew session 0x2616af5330a03c7 at /43.194.55.105:54576
host =	euegisdcosprdm01v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:28 euegisdcosprdm04v java[12453]: [myid:4] INFO  [ProcessThread(sid:4 cport:-1)::PrepRequestProcessor@486] - Processed session termination for sessionid: 0x2616af5330a03c7
host =	euegisdcosprdm04v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:28 euegisdcosprdm04v java[12453]: [myid:4] INFO  [SessionTracker:ZooKeeperServer@358] - Expiring session 0x2616af5330a03c7, timeout of 10000ms exceeded
host =	euegisdcosprdm04v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:24 euegisdcosprdm02v java[12463]: [myid:2] INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1044] - Closed socket connection for client /43.194.55.105:36678 which had sessionid 0x2616af5330a03c7
host =	euegisdcosprdm02v source =	journald-master sourcetype =	mesos:journald:master 	tier_3
Feb 23 14:38:24 euegisdcosprdm02v java[12463]: [myid:2] WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@368] - caught end of stream exception
                                               EndOfStreamException: Unable to read additional data from client sessionid 0x2616af5330a03c7, likely client has closed socket
                                                       at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:239)
                                                       at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
                                                       at java.lang.Thread.run(Thread.java:748)
```
Regards,
Kamil

### PR DESCRIPTION
**Pull request by adleong**
If a ZooKeeper watch is created on a session that expires, a new session will be created but the watch will remain on the expired session.  Furthermore, when Namerd encounters ZK errors, it signals that Linkerd should wait for a very long (10 minute) delay before retrying.  This leads to extremely slow recovery in the case of an error.

Fix the watch code to follow the new session in when a session expires.  Additionally, remove the ability for Namerd to signal retry delays to Linkerd and instead use the backoffs already configured in the client.

Fixes #1829

### CODE REVIEW

File: namerd/storage/zk/src/main/scala/com/twitter/finagle/serverset2/buoyant/ZkDtabStore.scala [hunk 1]
```diff
@@ -66,14 +70,16 @@ class ZkDtabStore(
...
+        log.error(e, "Failed to create dtab at %s", path)
       }.unit
   }
 
   def delete(ns: String): Future[Unit] = {
     val path = s"$zkPrefix/$ns"
     log.info("Attempting to delete dtab at %s", path)
 
-    zkSession.zk.delete(path, None).rescue {
+    zkSession.zk.sample.delete(path, None).rescue {
```
Comment (olix0r) [inline namerd/storage/zk/src/main/scala/com/twitter/finagle/serverset2/buoyant/ZkDtabStore.scala]: nit: i tend to think of `sample()` as side-effecty, and so I use parens.
