### PR TITLE
Reduce scariness of error message caused by misbehaving H2 clients

### LINKED ISSUE #1289: grpc-go helloworld app causes the h2 dispatcher to fail
I've been testing linkerd's gRPC support with v1.3.0 of both of the official [grpc-go](https://github.com/grpc/grpc-go/tree/master/examples) and the [grpc-java](https://github.com/grpc/grpc-java/tree/master/examples) example apps. Both apps successfully return a response, but the go app causes linkerd to log a "dispatcher failed" error. The same dispatch error does not show up when using the java app.

I'm using the following linkerd config:

```yaml
routers:
- protocol: h2
  experimental: true
  dtab: |
    /svc/* => /$/inet/localhost/50051;
  servers:
  - port: 4140
```

That forwards all traffic from 4140 to 50051, where the example servers are running.

I then followed the instructions in both projects to run the example server, and modified the example client to call port 4140, instead of 50051. Running the go client successfully returns a response, but in linkerd's logs, I see:

```
E 0510 00:19:07.027 UTC THREAD144: [S L:/127.0.0.1:4140 R:/127.0.0.1:63351] dispatcher failed
com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /127.0.0.1:63351. Remote Info: Not Available
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelInactive(ChannelTransport.scala:186)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelInactive(ChannelRequestStatsHandler.scala:36)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:390)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelInactive(ChannelStatsHandler.scala:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
	at java.lang.Thread.run(Thread.java:745)
```

The same error does not appear when using the java client, which also returns successfully.

### PR DESCRIPTION
**Pull request by hawkw**
Some gRPC clients (including the grpc-go client we use in `linkerd-examples/docker/helloworld`) fail to send GOAWAY frames after closing the connection. This was causing linkerd to log an error message which gave the impression that servicing the request in question had failed, when it had actually been completed successfully.

I consulted the HTTP/2 spec and found the following: 

> Endpoints SHOULD always send a GOAWAY frame before closing a connection so that the remote peer can know whether a stream has been partially processed or not. For example, if an HTTP client sends a POST at the same time that a server closes a connection, the client cannot know if the server started to process that POST request if the server does not send a GOAWAY frame to indicate what streams it might have acted on.

Therefore, it occurs these clients are, in fact, acting erroneously by not sending a GOAWAY frame, so it seems reasonable for linkerd to log some kind of message. However, since the stack trace previously being printed was scary and didn't accurately describe what was going on, I intercepted the exception and downgraded the log entry to a warning with a more explanatory message. Additionally, I ensured that this warning is only logged if all the streams have already been closed, since a `ConnectionClosedException` occurring when there are still streams open could be indicative of a bigger problem and should still be propagated.

I reproduced the bug using the `helloworld` example and the linkerd configs provided by @klingerf in issue #1289. After applying my fix, the spurious log message no longer appears, and is replaced with
```
W 0712 20:30:18.821 UTC THREAD573: [S L:/127.0.0.1:4140 R:/127.0.0.1:54802] client closed connection without sending GOAWAY frame
```

Fixes #1289

### CODE REVIEW

File: finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala [hunk 1]
```diff
@@ -105,6 +105,14 @@ trait Netty4DispatcherBase[SendMsg <: Message, RecvMsg <: Message] {
         log.debug(e, "[%s] dispatcher closed", prefix)
         Future.exception(e)
 
+      case Throw(e: ChannelClosedException)
+      // if all streams have already been closed, then this just means that
+      // the client failed to send a GOAWAY frame...
+      if closed.get || streams.keys.asScala.forall { _ <= closedId.get } =>
```
Comment (adleong) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: If I'm understanding correctly, streams should be removed from `streams` when they are closed.  So I think this can just be `closed.get || streams.isEmpty`.

File: finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala [hunk 2]
```diff
@@ -105,6 +105,14 @@ trait Netty4DispatcherBase[SendMsg <: Message, RecvMsg <: Message] {
...
+        // ...so we don't need to propagate the exception
+        log.warning("[%s] client closed connection without sending GOAWAY frame", prefix)
```
Comment (adleong) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: I'm torn about this.  Conceptually, I agree with you.  However, since some of the most widely used clients have this bad behavior, I worry about linkerd's logs just getting clogged with these messages.

File: finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala (hunk 1 above)
Comment (hawkw) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: Ah, I wasn't sure – I thought that was what the `closedId` was for?

File: finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala (hunk 2 above)
Comment (hawkw) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: Hmm. I could either make this completely silent, or have it log to `debug` if that seems more correct?

Comment (klingerf) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: `debug` sounds good to me.

Comment (hawkw) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: (an alternative, and perhaps more principled, solution to this issue: "we submit patches to `grpc-go` and the Python `grpcio` package fixing this behavior, but I think that would take work)

Comment (hawkw) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: Okay, logs as `debug` in d65c1dd5c3b60e6df34b06ed0408b1f96e4d488f.

File: finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala (hunk 1 above)
Comment (hawkw) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: Fixed d65c1dd5c3b60e6df34b06ed0408b1f96e4d488f

Comment (adleong) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: `closedId` is the highest closed stream id.  If we encounter a stream id that's not in our map, it might not be there because the stream was closed and removed from the map, or it might not be there because the stream hasn't been created yet.  closedId helps us differentiate those cases.  I think.

File: finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala [hunk 3]
```diff
@@ -105,6 +105,14 @@ trait Netty4DispatcherBase[SendMsg <: Message, RecvMsg <: Message] {
         log.debug(e, "[%s] dispatcher closed", prefix)
         Future.exception(e)
 
+      case Throw(e: ChannelClosedException)
+        // if all streams have already been closed, then this just means that
+        // the client failed to send a GOAWAY frame...
+        if closed.get || streams.isEmpty =>
```
Comment (klingerf) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: Super minor, but I don't think you need to `closed.get` check here, since the previous case is `Throw(e) if closed.get`. I'd be inclined to write this as:

```
case Throw(e) if closed.get =>
case Throw(e: ChannelClosedException) if streams.isEmpty =>
case Throw(e) =>
```

Comment (hawkw) [inline finagle/h2/src/main/scala/com/twitter/finagle/buoyant/h2/netty4/Netty4DispatcherBase.scala]: oh, you're right! l'll remove that, thanks
