### PR TITLE
Fix k8s namer to handle null ep subsets (#1219)

### LINKED ISSUE #1219: NullPointerException on Kubernetes 1.6.1
Linkerd Versions: 0.9.0 and 0.9.1 have same error
Kubernetes Versions: 1.6.1, 1.6.0

### Stack trace on linkerd 0.9.0
```
E 0417 21:47:41.726 UTC THREAD21: k8s failed to list endpoints
java.lang.NullPointerException
	at io.buoyant.k8s.EndpointsNamer$.io$buoyant$k8s$EndpointsNamer$$getAddrs(EndpointsNamer.scala:116)
	at io.buoyant.k8s.EndpointsNamer$.io$buoyant$k8s$EndpointsNamer$$mkPorts(EndpointsNamer.scala:145)
	at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$io$buoyant$k8s$EndpointsNamer$NsCache$$mkSvc$1.apply(EndpointsNamer.scala:246)
	at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$io$buoyant$k8s$EndpointsNamer$NsCache$$mkSvc$1.apply(EndpointsNamer.scala:245)
	at scala.Option.map(Option.scala:146)
	at io.buoyant.k8s.EndpointsNamer$NsCache.io$buoyant$k8s$EndpointsNamer$NsCache$$mkSvc(EndpointsNamer.scala:245)
	at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$10.apply(EndpointsNamer.scala:226)
	at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$10.apply(EndpointsNamer.scala:225)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at io.buoyant.k8s.EndpointsNamer$NsCache.initialize(EndpointsNamer.scala:225)
	at io.buoyant.k8s.EndpointsNamer$NsCache.initialize(EndpointsNamer.scala:213)
	at io.buoyant.k8s.Ns$$anonfun$io$buoyant$k8s$Ns$$watch$1$$anonfun$apply$1.apply(Ns.scala:77)
	at io.buoyant.k8s.Ns$$anonfun$io$buoyant$k8s$Ns$$watch$1$$anonfun$apply$1.apply(Ns.scala:76)
	at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$3.apply(Future.scala:1145)
	at com.twitter.util.Try$.apply(Try.scala:15)
```

### Stack trace on 0.9.1
```
I 0417 21:57:49.256 UTC THREAD1: linkerd 0.9.1
...
E 0417 21:57:52.349 UTC THREAD18: k8s failed to list endpoints
java.lang.NullPointerException
        at io.buoyant.k8s.EndpointsNamer$.io$buoyant$k8s$EndpointsNamer$$getEndpoints(EndpointsNamer.scala:126)
        at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$io$buoyant$k8s$EndpointsNamer$NsCache$$mkSvc$1.apply(EndpointsNamer.scala:221
        at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$io$buoyant$k8s$EndpointsNamer$NsCache$$mkSvc$1.apply(EndpointsNamer.scala:219
        at scala.Option.map(Option.scala:146)
        at io.buoyant.k8s.EndpointsNamer$NsCache.io$buoyant$k8s$EndpointsNamer$NsCache$$mkSvc(EndpointsNamer.scala:219)
        at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$13.apply(EndpointsNamer.scala:200)
        at io.buoyant.k8s.EndpointsNamer$NsCache$$anonfun$13.apply(EndpointsNamer.scala:199)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at io.buoyant.k8s.EndpointsNamer$NsCache.initialize(EndpointsNamer.scala:199)
        at io.buoyant.k8s.EndpointsNamer$NsCache.initialize(EndpointsNamer.scala:187)
        at io.buoyant.k8s.Ns$$anonfun$io$buoyant$k8s$Ns$$watch$1$$anonfun$apply$1.apply(Ns.scala:77)
        at io.buoyant.k8s.Ns$$anonfun$io$buoyant$k8s$Ns$$watch$1$$anonfun$apply$1.apply(Ns.scala:76)
        at com.twitter.util.Future$$anonfun$map$1$$anonfun$apply$3.apply(Future.scala:1145)
        at com.twitter.util.Try$.apply(Try.scala:15)
        at com.twitter.util.Future$.apply(Future.scala:163)
        at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:1145)
        at com.twitter.util.Future$$anonfun$map$1.apply(Future.scala:1144)
        at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
        at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
        at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
        at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
        at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
```
Full Stack Traces: https://gist.github.com/lkysow/d82d9d59bb6a7776418917560a0c95dd

With these errors Linkerd can't do any lookups and so no routing, i.e. it is essentially dead.

### PR DESCRIPTION
**Pull request by siggy**
In Kubernetes 1.6.1, the EndpointsList API changed so that the `subsets`
field may be null.

To resolve this, subsets have been made optional.

A test case has been added to validate this.

Fixes #1219

### CODE REVIEW

File: k8s/src/main/scala/io/buoyant/k8s/EndpointsNamer.scala [hunk 1]
```diff
@@ -120,10 +120,10 @@ private object EndpointsNamer {
 
   case class Svc(endpoints: Set[Endpoint], ports: Map[String, Int])
 
-  private[this] def getEndpoints(subsets: Seq[v1.EndpointSubset]): Set[Endpoint] = {
+  private[this] def getEndpoints(subsets: Option[Seq[v1.EndpointSubset]]): Set[Endpoint] = {
     val endpoints = mutable.Set.empty[Endpoint]
     for {
-      subset <- subsets
+      subset <- subsets.getOrElse(Seq[v1.EndpointSubset]())
```
Comment (olix0r) [inline k8s/src/main/scala/io/buoyant/k8s/EndpointsNamer.scala]: prefer `Seq.empty`

File: k8s/src/main/scala/io/buoyant/k8s/EndpointsNamer.scala [hunk 2]
```diff
@@ -132,10 +132,10 @@ private object EndpointsNamer {
     endpoints.toSet
   }
 
-  private[this] def getPorts(subsets: Seq[v1.EndpointSubset]): Map[String, Int] = {
+  private[this] def getPorts(subsets: Option[Seq[v1.EndpointSubset]]): Map[String, Int] = {
     val portSet = mutable.Map.empty[String, Int]
     for {
-      subset <- subsets
+      subset <- subsets.getOrElse(Seq[v1.EndpointSubset]())
```
Comment (olix0r) [inline k8s/src/main/scala/io/buoyant/k8s/EndpointsNamer.scala]: prefer Seq.empty
