### PR TITLE
Fixes #1552 - Rework TLS client configuration trust store to use a CA…

### LINKED ISSUE #1552: Remove dependence on temp files for TLS certificates
We experienced an issue where several of our linkerd instances started failing with this error message: 

```
Aug 02 14:53:29 store-app1-i.sjc1sl.bigcommerce.net linkerd[25890]: Caused by: java.security.cert.CertificateException: could not find certificate file: /tmp/certCollection3425953256568330028.tmp
```

It turns out that it was trying to read a file out of the temp directory that had been cleaned out by a cron job that deletes files in the server's temp directory that hadn't been modified after a week. 

If these files are required for an extended period of time, linkerd shouldn't store them in the system's temp directory. 

The dependence on these temp files appears to be introduced in this PR for mutual TLS: https://github.com/linkerd/linkerd/pull/1319/files#diff-c23f3271d49c726272f66f9c10e24b3aR29

### PR DESCRIPTION
**Pull request by dvulpe**
… bundle instead of dropping all ca certs to a bundle in the temp folder. This simplifies the client TLS code, removes a dependency on the temporary folder and aligns client TLS configuration with server TLS configuration.

TLS client configuration still supports the former trustCerts option which if it's used it will cause a warning to be logged.

Sample from the logs:
```
W 0610 17:49:05.788 BST THREAD1: trustCerts configuration option is deprecated, please consider using trustCertsBundle
```

Signed-off-by: Dan Vulpe <dvulpe@gmail.com>

### CODE REVIEW

**Comment by adleong** [comment]
Thank you, @dvulpe!  Removing our dependency on temp files will be so awesome.  I'm really looking forward to reviewing this.

File: finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala [hunk 1]
```diff
@@ -31,33 +31,17 @@ case class TlsClientConfig(
...
-        val certCollection = File.createTempFile("certCollection", null)
-        // open the cert paths as Streams...
-        val f = new FileOutputStream(certCollection)
-        for {
-          cert <- certs
-          certStream = new FileInputStream(cert)
-        } { // ...and copy the certs into the cert collection
-          // TODO: can this be made more concise with scala.io?
-          StreamIO.copy(certStream, f)
+    case TlsClientConfig(_, _, Some(cn), certs, bundle, clientAuth, enabledProtocols) =>
```
Comment (adleong) [inline finagle/buoyant/src/main/scala/com/twitter/finagle/buoyant/TlsClientConfig.scala]: I'd prefer to be a bit more defensive here and throw an IllegalArgumentException if trustCerts and trustCertsBundle are both set.  Then we can handle them in separate cases:

```
case TlsClientConfig(_, _, Some(cn), Some(certs), Some(bundle), _, _) =>
  throw ...
case TlsClientConfig(_, _, Some(cn), Some(certs), None, _, _) =>
  // use certs
case TlsClientConfig(_, _, Some(cn), None, Some(bundle), _, _) =>
  // use bundle
case TlsClientConfig(_, _, Some(cn), None, None, _, _) =>
  // use Unspecified
```

**Comment by dvulpe** [comment]
Nice one, thanks! I look forward to my next contribution to this great project!
