### PR TITLE
Make ConfigMapInterpreter handle errors gracefully

### LINKED ISSUE #1639: Invalid dtab ConfigMap prevents further updates
Hello,

Using the io.l5d.k8s.configMap interpreter I provide a dtab file with a syntax error, which causes an java.lang.IllegalArgumentException in Finagle:

```
at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:28)
--
  | at com.twitter.finagle.NameTreeParsers.illegal(NameTreeParsers.scala:38)
  | at com.twitter.finagle.NameTreeParsers.eat(NameTreeParsers.scala:54)
  | at com.twitter.finagle.NameTreeParsers.parseDentryPrefix(NameTreeParsers.scala:148)
  | at com.twitter.finagle.NameTreeParsers.parseDentry(NameTreeParsers.scala:256)
  | at com.twitter.finagle.NameTreeParsers.parseDtab(NameTreeParsers.scala:270)
  | at com.twitter.finagle.NameTreeParsers.parseAllDtab(NameTreeParsers.scala:307)
  | at com.twitter.finagle.NameTreeParsers$.parseDtab(NameTreeParsers.scala:11)
  | at com.twitter.finagle.Dtab$.read(Dtab.scala:355)
  | at io.buoyant.interpreter.k8s.ConfigMapInterpreterConfig.getDtab(ConfigMapInterpreterInitializer.scala:80)
  | at io.buoyant.interpreter.k8s.ConfigMapInterpreterConfig.$anonfun$extractDtab$1(ConfigMapInterpreterInitializer.scala:69)
  | at scala.Option.map(Option.scala:146)
  | at io.buoyant.interpreter.k8s.ConfigMapInterpreterConfig.extractDtab(ConfigMapInterpreterInitializer.scala:69)
  | at io.buoyant.interpreter.k8s.ConfigMapInterpreterConfig.$anonfun$act$1(ConfigMapInterpreterInitializer.scala:52)
  | at io.buoyant.k8s.Watchable.$anonfun$activity$3(Watchable.scala:206)
  | at io.buoyant.k8s.Watchable.$anonfun$activity$3$adapted(Watchable.scala:205)
  | at com.twitter.util.Future.$anonfun$onSuccess$1(Future.scala:1205)
  | at com.twitter.util.Future.$anonfun$onSuccess$1$adapted(Future.scala:1204)
  | at com.twitter.util.Promise$Monitored.apply(Promise.scala:202)
  | at com.twitter.util.Promise$Monitored.apply(Promise.scala:193)
  | at com.twitter.util.Promise$$anon$7.run(Promise.scala:545)
  | at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
  | at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
  | at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
  | at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
  | at com.twitter.util.Promise.runq(Promise.scala:520)
  | at com.twitter.util.Promise.updateIfEmpty(Promise.scala:883)
  | at com.twitter.util.Promise.update(Promise.scala:857)
  | at com.twitter.util.Promise.setValue(Promise.scala:833)
  | at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
  | at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:181)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at com.twitter.finagle.netty4.http.handler.ClientExceptionMapper$.channelRead(ClientExceptionMapper.scala:33)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
  | at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
  | at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
  | at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
  | at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
  | at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
  | at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
  | at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
  | at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
  | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
  | at java.lang.Thread.run(Thread.java:748)
```
After this exception all further updates of the ConfigMap are not taken into account: linkerd routes using the last good dtab before the corrupted one.

Furthermore, if I update the page of delegator playground before doing any routing requests, the playground stops working showing "The request to namerd has timed out. Please ensure your config is correct and try again." And never comes back, even after submitting a good dtab. Moreover linkerd stops replying. Then it may reply once and stops again.

I see also 
`E 0914 15:15:57.061 UTC THREAD35 TraceId:9bd2b8cb39306110: service failure: com.twitter.finagle.CancelledConnectionException
`

### PR DESCRIPTION
**Pull request by hawkw**
When a `ConfigMapInterpreter` receives a `MODIFIED` event containing an invalid dtab, it falls back to the last good observed dtab, as intended. However, after falling back to the last good dtab, Linkerd currently refuses to honor any future `MODIFIED` events to the ConfigMap, even if they contain valid dtabs.

I've modified `ConfigMapInterpreterInitializer` to rectify this behavior. The `getDtab` function now returns a `Try`, rather than throwing an exception.

I've added a unit test reproducing #1639 with real Kubernetes events I generated using our GKE cluster. Previously, there were no unit tests for `ConfigMapInterpreter`'s event handling, only for the correct initialization of the interpreter. I've rectified this situation by adding several other tests for the correctness of the interpreter's event handling as well. In order to write these tests, I also had to modify the `ConfigMapInterpreterInitializer` to allow a mock Kubernetes API object to be injected.

Fixes #1639

### CODE REVIEW

File: interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala [hunk 1]
```diff
@@ -41,48 +50,63 @@ case class ConfigMapInterpreterConfig(
...
     }
 
   @JsonIgnore
   override def newInterpreter(params: Params): NameInterpreter = {
     val Param.Namers(namers) = params[Param.Namers]
     ConfiguredDtabNamer(act, namers)
   }
+
+  @JsonIgnore
+  private[this] object ConfigMapDtab {
```
Comment (adleong) [inline interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Just my 2c but I think this extractor makes this code harder to follow rather than easier.  I would just keep those cases inline in the match above, even if it is a *tiny* amount of duplication.

File: interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala [hunk 2]
```diff
@@ -41,48 +50,63 @@ case class ConfigMapInterpreterConfig(
...
   @JsonIgnore
-  def getDtab(configMap: ConfigMap): Dtab =
+  def getDtab(configMap: ConfigMap): Try[Dtab] =
     configMap.data.get(filename) match {
       case None =>
         log.warning(s"dtab at %s in k8s ConfigMap %s did not exist!", filename, name)
-        Dtab.empty
-      case Some(data) => Dtab.read(data)
+        Return(Dtab.empty)
+      case Some(data) => Try(Dtab.read(data))
```
Comment (adleong) [inline interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: TIOLI: I think you could leave the existing signature the same if you changed this to

```
Try(Dtab.read(data)).getOrElse(Dtab.empty)
```

or

```
try { Dtab.read(data) } catch { case _: IllegalArgumentException =>
  log.warning(...)
  Dtab.empty
}
```

File: interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala [hunk 3]
```diff
@@ -26,12 +26,21 @@ case class ConfigMapInterpreterConfig(
   port: Option[Port],
   namespace: Option[String],
   name: String,
-  filename: String
+  filename: String,
+  mkApi: Option[() => NsApi] = None
```
[the remark this answers is not in the document]
Comment (hawkw) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Ah, yeah, that makes a lot more sense, I really wish I had thought of that.

File: interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala (hunk 1 above)
Comment (hawkw) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: but Alex, DRY! :(

File: interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala (hunk 2 above)
Comment (hawkw) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Hmm, this changes the semantics somewhat: if we want to fall back to the previous dtab on an error, rather than returning `Dtab.empty`, the error needs to at least propagate up to `Activity.onEvent`, where the previous dtab value is known...

**Comment by hawkw** [comment]
@adleong, I think I've addressed all the changes you've requested?

File: interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala [hunk 4]
```diff
@@ -41,7 +42,7 @@ case class ConfigMapInterpreterConfig(
   private[this] val log = Logger()
 
   @JsonIgnore
-  val api = {
+  def api = {
```
Comment (adleong) [inline interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Doesn't this create a new client for every time `api` is referenced?

Comment (hawkw) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Yes, but `api` is only referenced once, and leaving this as a `val` causes [the test interpreter](https://github.com/linkerd/linkerd/pull/1640/commits/4c3b885c60e56a8e67b6d3b7e5e458587597d301#diff-fe9d877a01176ddad3635ce17d9e22c7R163) to throw a `NullPointerException`.

Comment (adleong) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Scala: where the only thing more insane than the problems are the solutions.

```
object TestConfigMapInterpreterConfig extends {
  override val api = v1.Api(service).withNamespace("test")
} with ConfigMapInterpreterConfig(
  None, None, Some("test"), "test-config", "test.dtab"
) {
```

Comment (hawkw) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: Jesus Christ. That fixes it???? I didn't even know you _could_ extend `{ .. }`, I thought you could only do `new ConfigMapInterpreter(...) { ... }`

Comment (adleong) [reply interpreter/k8s/src/main/scala/io/buoyant/interpreter/k8s/ConfigMapInterpreterInitializer.scala]: These little corners of the language are so disgusting yet fascinating.

**Comment by hawkw** [comment]
@adleong I think now that I've made the changes you've asked for in e8e7eb1, this should be ready to merge?
